package models;

public enum ActivityType {
    ADDED_SERVICE,
    UPDATED_SERVICE,
    APPLIED_SERVICE,
    CANCEL_APPLICATION_SERVICE,
    REJECTED_SERVICE_OFFER,
    STARTED_SERVICE,
    FINISHED_SERVICE,
    COMMENTED_ON,
    PROPOSED_TASK,
    VOTED_ON_TASK,
    TASK_APPROVED,
    REWARD_GIVEN
}
